package com.training.DAO;
// default package
// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1



import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AddressDetailsId generated by hbm2java
 */
@Embeddable
public class AddressDetailsId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userId;
	private int doorno;

	public AddressDetailsId() {
	}

	public AddressDetailsId(String userId, int doorno) {
		this.userId = userId;
		this.doorno = doorno;
	}

	@Column(name = "user_id", nullable = false, length = 6)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "doorno", nullable = false)
	public int getDoorno() {
		return this.doorno;
	}

	public void setDoorno(int doorno) {
		this.doorno = doorno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AddressDetailsId))
			return false;
		AddressDetailsId castOther = (AddressDetailsId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& (this.getDoorno() == castOther.getDoorno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + this.getDoorno();
		return result;
	}

}
