package com.training.dao;
// default package
// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1



import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemFormat generated by hbm2java
 */
@Entity
@Table(name = "item_format", catalog = "onlinelibrary")
public class ItemFormat implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ItemFormatId id;
	private LibraryItems libraryItems;
	private String available;

	public ItemFormat() {
	}

	public ItemFormat(ItemFormatId id, LibraryItems libraryItems, String available) {
		this.id = id;
		this.libraryItems = libraryItems;
		this.available = available;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "itemId", column = @Column(name = "item_id", nullable = false, length = 8)),
			@AttributeOverride(name = "itemType", column = @Column(name = "item_type", nullable = false, length = 6)) })
	public ItemFormatId getId() {
		return this.id;
	}

	public void setId(ItemFormatId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id", nullable = false, insertable = false, updatable = false)
	public LibraryItems getLibraryItems() {
		return this.libraryItems;
	}

	public void setLibraryItems(LibraryItems libraryItems) {
		this.libraryItems = libraryItems;
	}

	@Column(name = "available", nullable = false, length = 150)
	public String getAvailable() {
		return this.available;
	}

	public void setAvailable(String available) {
		this.available = available;
	}

}
