package com.training.dao;
// default package
// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LibraryItems generated by hbm2java
 */
@Entity
@Table(name = "library_items", catalog = "onlinelibrary")
public class LibraryItems implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String itemId;
	private String itemName;
	private Integer year;
	private int price;
	private String description;
	private String itemType;
	private Date dateAdded;
	private Date createdTime;
	private Date modifiedTime;
	private Set<?> ratingTables = new HashSet<Object>(0);
	private Set<?> likedLists = new HashSet<Object>(0);
	private Set<?> wishLists = new HashSet<Object>(0);
	private Books books;
	private Music music;
	private Movies movies;
	private Set<?> subscribedLists = new HashSet<Object>(0);
	private Set<?> itemFormats = new HashSet<Object>(0);

	public LibraryItems() {
	}

	public LibraryItems(String itemId, String itemName, int price, String description, String itemType, Date dateAdded,
			Date createdTime, Date modifiedTime) {
		this.itemId = itemId;
		this.itemName = itemName;
		this.price = price;
		this.description = description;
		this.itemType = itemType;
		this.dateAdded = dateAdded;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
	}

	public LibraryItems(String itemId, String itemName, Integer year, int price, String description, String itemType,
			Date dateAdded, Date createdTime, Date modifiedTime, Set<?> ratingTables, Set<?> likedLists, Set<?> wishLists, Books books,
			Music music, Movies movies, Set<?> subscribedLists, Set<?> itemFormats) {
		this.itemId = itemId;
		this.itemName = itemName;
		this.year = year;
		this.price = price;
		this.description = description;
		this.itemType = itemType;
		this.dateAdded = dateAdded;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.ratingTables = ratingTables;
		this.likedLists = likedLists;
		this.wishLists = wishLists;
		this.books = books;
		this.music = music;
		this.movies = movies;
		this.subscribedLists = subscribedLists;
		this.itemFormats = itemFormats;
	}

	@Id

	@Column(name = "item_id", unique = true, nullable = false, length = 8)
	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	@Column(name = "item_name", nullable = false, length = 50)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "description", nullable = false, length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "item_type", nullable = false, length = 10)
	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_added", nullable = false, length = 10)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", nullable = false, length = 19)
	public Date getcreatedTime() {
		return this.createdTime;
	}

	public void setcreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", nullable = false, length = 19)
	public Date getmodifiedTime() {
		return this.modifiedTime;
	}

	public void setmodifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "libraryItems")
	public Set<?> getRatingTables() {
		return this.ratingTables;
	}

	public void setRatingTables(Set<?> ratingTables) {
		this.ratingTables = ratingTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "libraryItems")
	public Set<?> getLikedLists() {
		return this.likedLists;
	}

	public void setLikedLists(Set<?> likedLists) {
		this.likedLists = likedLists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "libraryItems")
	public Set<?> getWishLists() {
		return this.wishLists;
	}

	public void setWishLists(Set<?> wishLists) {
		this.wishLists = wishLists;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "libraryItems")
	public Books getBooks() {
		return this.books;
	}

	public void setBooks(Books books) {
		this.books = books;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "libraryItems")
	public Music getMusic() {
		return this.music;
	}

	public void setMusic(Music music) {
		this.music = music;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "libraryItems")
	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "libraryItems")
	public Set<?> getSubscribedLists() {
		return this.subscribedLists;
	}

	public void setSubscribedLists(Set<?> subscribedLists) {
		this.subscribedLists = subscribedLists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "libraryItems")
	public Set<?> getItemFormats() {
		return this.itemFormats;
	}

	public void setItemFormats(Set<?> itemFormats) {
		this.itemFormats = itemFormats;
	}

}
