package com.training.DAO;
// default package
// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name = "user_details", catalog = "onlinelibrary")
public class UserDetails implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userId;
	private String userName;
	private String role;
	private int age;
	private String gender;
	private String languages;
	private String preferredNotify;
	private Date CTime;
	private Date MTime;
	private UserContactDetails userContactDetails;
	private Set<?> likedLists = new HashSet<Object>(0);
	private Set<?> ratingTables = new HashSet<Object>(0);
	private LoginDetails loginDetails;
	private Set<?> memberDetailses = new HashSet<Object>(0);

	public UserDetails() {
	}

	public UserDetails(String userId, String userName, String role, int age, String gender, String languages,
			String preferredNotify, Date CTime, Date MTime) {
		this.userId = userId;
		this.userName = userName;
		this.role = role;
		this.age = age;
		this.gender = gender;
		this.languages = languages;
		this.preferredNotify = preferredNotify;
		this.CTime = CTime;
		this.MTime = MTime;
	}

	public UserDetails(String userId, String userName, String role, int age, String gender, String languages,
			String preferredNotify, Date CTime, Date MTime, UserContactDetails userContactDetails, Set<?> likedLists,
			Set<?> ratingTables, LoginDetails loginDetails, Set<?> memberDetailses) {
		this.userId = userId;
		this.userName = userName;
		this.role = role;
		this.age = age;
		this.gender = gender;
		this.languages = languages;
		this.preferredNotify = preferredNotify;
		this.CTime = CTime;
		this.MTime = MTime;
		this.userContactDetails = userContactDetails;
		this.likedLists = likedLists;
		this.ratingTables = ratingTables;
		this.loginDetails = loginDetails;
		this.memberDetailses = memberDetailses;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false, length = 6)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "role", nullable = false, length = 1)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "gender", nullable = false, length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "languages", nullable = false, length = 100)
	public String getLanguages() {
		return this.languages;
	}

	public void setLanguages(String languages) {
		this.languages = languages;
	}

	@Column(name = "preferred_notify", nullable = false, length = 5)
	public String getPreferredNotify() {
		return this.preferredNotify;
	}

	public void setPreferredNotify(String preferredNotify) {
		this.preferredNotify = preferredNotify;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", nullable = false, length = 19)
	public Date getCTime() {
		return this.CTime;
	}

	public void setCTime(Date CTime) {
		this.CTime = CTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", nullable = false, length = 19)
	public Date getMTime() {
		return this.MTime;
	}

	public void setMTime(Date MTime) {
		this.MTime = MTime;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public UserContactDetails getUserContactDetails() {
		return this.userContactDetails;
	}

	public void setUserContactDetails(UserContactDetails userContactDetails) {
		this.userContactDetails = userContactDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<?> getLikedLists() {
		return this.likedLists;
	}

	public void setLikedLists(Set<?> likedLists) {
		this.likedLists = likedLists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<?> getRatingTables() {
		return this.ratingTables;
	}

	public void setRatingTables(Set<?> ratingTables) {
		this.ratingTables = ratingTables;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public LoginDetails getLoginDetails() {
		return this.loginDetails;
	}

	public void setLoginDetails(LoginDetails loginDetails) {
		this.loginDetails = loginDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
	public Set<?> getMemberDetailses() {
		return this.memberDetailses;
	}

	public void setMemberDetailses(Set<?> memberDetailses) {
		this.memberDetailses = memberDetailses;
	}

}
