package com.training.entity;
// default package

// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AddressDetailsId generated by hbm2java
 */
@Embeddable
public class AddressDetailsId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column(name = "user_id", nullable = false, length = 6)
	private String userId;

	@Column(name = "doorno", nullable = false)
	private int doorno;

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public int getDoorno() {
		return this.doorno;
	}

	public void setDoorno(int doorno) {
		this.doorno = doorno;
	}

}
