package com.training.entity;
// default package

// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LoginAuditId generated by hbm2java
 */
@Embeddable
public class LoginAuditId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column(name = "user_id", nullable = false, length = 6)
	private String userId;

	@Column(name = "last_login_time", nullable = false, length = 19)
	private Date lastLoginTime;

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginAuditId))
			return false;
		LoginAuditId castOther = (LoginAuditId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getLastLoginTime() == castOther.getLastLoginTime())
						|| (this.getLastLoginTime() != null && castOther.getLastLoginTime() != null
								&& this.getLastLoginTime().equals(castOther.getLastLoginTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getLastLoginTime() == null ? 0 : this.getLastLoginTime().hashCode());
		return result;
	}

}
