package com.training.entity;
// default package

// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberDetails generated by hbm2java
 */
@Entity
@Table(name = "member_details")
public class MemberDetails implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "member_id", unique = true, nullable = false)
	private Integer memberId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "membership_type_id", nullable = false)
	private MembershipDetails membershipDetails;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	private UserDetails userDetails;

	@Temporal(TemporalType.DATE)
	@Column(name = "enrolled_date", nullable = false, length = 10)
	private Date enrolledDate;

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 10)
	private Date endDate;

	@Temporal(TemporalType.DATE)
	@Column(name = "renewal_date", nullable = false, length = 10)
	private Date renewalDate;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", nullable = false, length = 19)
	private Date createdTime;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", nullable = false, length = 19)
	private Date modifiedTime;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memberDetails")
	private Set<?> wishLists = new HashSet<Object>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memberDetails")
	private Set<?> subscribedLists = new HashSet<Object>(0);

	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	public MembershipDetails getMembershipDetails() {
		return this.membershipDetails;
	}

	public void setMembershipDetails(MembershipDetails membershipDetails) {
		this.membershipDetails = membershipDetails;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public Date getEnrolledDate() {
		return this.enrolledDate;
	}

	public void setEnrolledDate(Date enrolledDate) {
		this.enrolledDate = enrolledDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getRenewalDate() {
		return this.renewalDate;
	}

	public void setRenewalDate(Date renewalDate) {
		this.renewalDate = renewalDate;
	}

	public Date getcreatedTime() {
		return this.createdTime;
	}

	public void setcreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getmodifiedTime() {
		return this.modifiedTime;
	}

	public void setmodifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public Set<?> getWishLists() {
		return this.wishLists;
	}

	public void setWishLists(Set<?> wishLists) {
		this.wishLists = wishLists;
	}

	public Set<?> getSubscribedLists() {
		return this.subscribedLists;
	}

	public void setSubscribedLists(Set<?> subscribedLists) {
		this.subscribedLists = subscribedLists;
	}

}
