package com.training.entity;
// default package

// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MembershipDetailsId generated by hbm2java
 */
@Embeddable
public class MembershipDetailsId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column(name = "member_type_id", nullable = false)
	private int memberTypeId;

	@Column(name = "membership_type", nullable = false, length = 6)
	private String membershipType;

	public int getMemberTypeId() {
		return this.memberTypeId;
	}

	public void setMemberTypeId(int memberTypeId) {
		this.memberTypeId = memberTypeId;
	}

	public String getMembershipType() {
		return this.membershipType;
	}

	public void setMembershipType(String membershipType) {
		this.membershipType = membershipType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MembershipDetailsId))
			return false;
		MembershipDetailsId castOther = (MembershipDetailsId) other;

		return (this.getMemberTypeId() == castOther.getMemberTypeId())
				&& ((this.getMembershipType() == castOther.getMembershipType())
						|| (this.getMembershipType() != null && castOther.getMembershipType() != null
								&& this.getMembershipType().equals(castOther.getMembershipType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMemberTypeId();
		result = 37 * result + (getMembershipType() == null ? 0 : this.getMembershipType().hashCode());
		return result;
	}

}
