package com.training.entity;
// default package
// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MembershipDetails generated by hbm2java
 */
@Entity
@Table(name = "membership_details", catalog = "onlinelibrary")
public class MembershipDetails implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MembershipDetailsId id;
	private int maxPriceLimit;
	private int validityDays;
	private int membershipCost;
	private Date createdTime;
	private Date modifiedTime;
	private Set<?> memberDetailses = new HashSet<Object>(0);

	public MembershipDetails() {
	}

	public MembershipDetails(MembershipDetailsId id, int maxPriceLimit, int validityDays, int membershipCost,
			Date createdTime, Date modifiedTime) {
		this.id = id;
		this.maxPriceLimit = maxPriceLimit;
		this.validityDays = validityDays;
		this.membershipCost = membershipCost;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
	}

	public MembershipDetails(MembershipDetailsId id, int maxPriceLimit, int validityDays, int membershipCost,
			Date createdTime, Date modifiedTime, Set<?> memberDetailses) {
		this.id = id;
		this.maxPriceLimit = maxPriceLimit;
		this.validityDays = validityDays;
		this.membershipCost = membershipCost;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.memberDetailses = memberDetailses;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "memberTypeId", column = @Column(name = "member_type_id", nullable = false)),
			@AttributeOverride(name = "membershipType", column = @Column(name = "membership_type", nullable = false, length = 6)) })
	public MembershipDetailsId getId() {
		return this.id;
	}

	public void setId(MembershipDetailsId id) {
		this.id = id;
	}

	@Column(name = "max_price_limit", nullable = false)
	public int getMaxPriceLimit() {
		return this.maxPriceLimit;
	}

	public void setMaxPriceLimit(int maxPriceLimit) {
		this.maxPriceLimit = maxPriceLimit;
	}

	@Column(name = "validity_days", nullable = false)
	public int getValidityDays() {
		return this.validityDays;
	}

	public void setValidityDays(int validityDays) {
		this.validityDays = validityDays;
	}

	@Column(name = "membership_cost", nullable = false)
	public int getMembershipCost() {
		return this.membershipCost;
	}

	public void setMembershipCost(int membershipCost) {
		this.membershipCost = membershipCost;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", nullable = false, length = 19)
	public Date getcreatedTime() {
		return this.createdTime;
	}

	public void setcreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", nullable = false, length = 19)
	public Date getmodifiedTime() {
		return this.modifiedTime;
	}

	public void setmodifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "membershipDetails")
	public Set<?> getMemberDetailses() {
		return this.memberDetailses;
	}

	public void setMemberDetailses(Set<?> memberDetailses) {
		this.memberDetailses = memberDetailses;
	}

}
