package com.training.entity;
// default package

// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * UserContactDetails generated by hbm2java
 */
@Entity
@Table(name = "user_contact_details", catalog = "onlinelibrary", uniqueConstraints = {
		@UniqueConstraint(columnNames = "email_id"), @UniqueConstraint(columnNames = "mobile_no") })
public class UserContactDetails implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userDetails"))
	@Id
	@GeneratedValue(generator = "generator")
	@JsonIgnore

	@Column(name = "user_id", unique = true, nullable = false, length = 6)
	private String userId;
	
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private UserDetails userDetails;
	
	@Column(name = "email_id", unique = true, nullable = false, length = 35)
	private String emailId;
	
	@Column(name = "mobile_no", unique = true, nullable = false)
	private int mobileNo;
	
	@Column(name = "alternate_contact_no")
	private Integer alternateContactNo;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", nullable = false, length = 19)
	private Date createdTime;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", nullable = false, length = 19)
	private Date modifiedTime;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userContactDetails")
	private List<AddressDetails> addressDetailses;

	
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	
	public int getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(int mobileNo) {
		this.mobileNo = mobileNo;
	}

	
	public Integer getAlternateContactNo() {
		return this.alternateContactNo;
	}

	public void setAlternateContactNo(Integer alternateContactNo) {
		this.alternateContactNo = alternateContactNo;
	}

	
	public Date getcreatedTime() {
		return this.createdTime;
	}

	public void setcreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	
	public Date getmodifiedTime() {
		return this.modifiedTime;
	}

	public void setmodifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	
	public List<AddressDetails> getAddressDetailses() {
		return this.addressDetailses;
	}

	public void setAddressDetailses(List<AddressDetails> addressDetailses) {
		this.addressDetailses = addressDetailses;
	}

}
