package com.training.entity;
// default package
// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserContactDetails generated by hbm2java
 */
@Entity
@Table(name = "user_contact_details", catalog = "onlinelibrary", uniqueConstraints = {
		@UniqueConstraint(columnNames = "email_id"), @UniqueConstraint(columnNames = "mobile_no") })
public class UserContactDetails implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userId;
	private UserDetails userDetails;
	private String emailId;
	private int mobileNo;
	private Integer alternateContactNo;
	private Date createdTime;
	private Date modifiedTime;
	private Set<?> addressDetailses = new HashSet<Object>(0);

	public UserContactDetails() {
	}

	public UserContactDetails(UserDetails userDetails, String emailId, int mobileNo, Date createdTime, Date modifiedTime) {
		this.userDetails = userDetails;
		this.emailId = emailId;
		this.mobileNo = mobileNo;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
	}

	public UserContactDetails(UserDetails userDetails, String emailId, int mobileNo, Integer alternateContactNo,
			Date createdTime, Date modifiedTime, Set<?> addressDetailses) {
		this.userDetails = userDetails;
		this.emailId = emailId;
		this.mobileNo = mobileNo;
		this.alternateContactNo = alternateContactNo;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.addressDetailses = addressDetailses;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userDetails"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "user_id", unique = true, nullable = false, length = 6)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "email_id", unique = true, nullable = false, length = 35)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "mobile_no", unique = true, nullable = false)
	public int getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(int mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "alternate_contact_no")
	public Integer getAlternateContactNo() {
		return this.alternateContactNo;
	}

	public void setAlternateContactNo(Integer alternateContactNo) {
		this.alternateContactNo = alternateContactNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", nullable = false, length = 19)
	public Date getcreatedTime() {
		return this.createdTime;
	}

	public void setcreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", nullable = false, length = 19)
	public Date getmodifiedTime() {
		return this.modifiedTime;
	}

	public void setmodifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userContactDetails")
	public Set<?> getAddressDetailses() {
		return this.addressDetailses;
	}

	public void setAddressDetailses(Set<?> addressDetailses) {
		this.addressDetailses = addressDetailses;
	}

}
