package com.training.pojos;
// default package
// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1



import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AddressDetails generated by hbm2java
 */
@Entity
@Table(name = "address_details", catalog = "onlinelibrary")
public class AddressDetails implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AddressDetailsId id;
	private UserContactDetails userContactDetails;
	private String streetName;
	private int pinCode;
	private String city;
	private String state;
	private String country;

	public AddressDetails() {
	}

	public AddressDetails(AddressDetailsId id, UserContactDetails userContactDetails, int pinCode, String city,
			String state, String country) {
		this.id = id;
		this.userContactDetails = userContactDetails;
		this.pinCode = pinCode;
		this.city = city;
		this.state = state;
		this.country = country;
	}

	public AddressDetails(AddressDetailsId id, UserContactDetails userContactDetails, String streetName, int pinCode,
			String city, String state, String country) {
		this.id = id;
		this.userContactDetails = userContactDetails;
		this.streetName = streetName;
		this.pinCode = pinCode;
		this.city = city;
		this.state = state;
		this.country = country;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 6)),
			@AttributeOverride(name = "doorno", column = @Column(name = "doorno", nullable = false)) })
	public AddressDetailsId getId() {
		return this.id;
	}

	public void setId(AddressDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public UserContactDetails getUserContactDetails() {
		return this.userContactDetails;
	}

	public void setUserContactDetails(UserContactDetails userContactDetails) {
		this.userContactDetails = userContactDetails;
	}

	@Column(name = "street_name", length = 50)
	public String getStreetName() {
		return this.streetName;
	}

	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	@Column(name = "pin_code", nullable = false)
	public int getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(int pinCode) {
		this.pinCode = pinCode;
	}

	@Column(name = "city", nullable = false, length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", nullable = false, length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", nullable = false, length = 20)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
