package com.training.pojos;
// default package
// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LikedList generated by hbm2java
 */
@Entity
@Table(name = "liked_list", catalog = "onlinelibrary")
public class LikedList implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private LikedListId id;
	private LibraryItems libraryItems;
	private UserDetails userDetails;
	private int likeStatus;
	private Date cTime;
	private Date mTime;

	public LikedList() {
	}

	public LikedList(LikedListId id, LibraryItems libraryItems, UserDetails userDetails, int likeStatus, Date cTime,
			Date mTime) {
		this.id = id;
		this.libraryItems = libraryItems;
		this.userDetails = userDetails;
		this.likeStatus = likeStatus;
		this.cTime = cTime;
		this.mTime = mTime;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 6)),
			@AttributeOverride(name = "itemId", column = @Column(name = "item_id", nullable = false, length = 8)) })
	public LikedListId getId() {
		return this.id;
	}

	public void setId(LikedListId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id", nullable = false, insertable = false, updatable = false)
	public LibraryItems getLibraryItems() {
		return this.libraryItems;
	}

	public void setLibraryItems(LibraryItems libraryItems) {
		this.libraryItems = libraryItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "like_status", nullable = false)
	public int getLikeStatus() {
		return this.likeStatus;
	}

	public void setLikeStatus(int likeStatus) {
		this.likeStatus = likeStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", nullable = false, length = 19)
	public Date getcTime() {
		return this.cTime;
	}

	public void setcTime(Date cTime) {
		this.cTime = cTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", nullable = false, length = 19)
	public Date getmTime() {
		return this.mTime;
	}

	public void setmTime(Date mTime) {
		this.mTime = mTime;
	}

}
