package com.training.pojos;
// default package
// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberDetails generated by hbm2java
 */
@Entity
@Table(name = "member_details", catalog = "onlinelibrary")
public class MemberDetails implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer memberId;
	private MembershipDetails membershipDetails;
	private UserDetails userDetails;
	private Date enrolledDate;
	private Date endDate;
	private Date renewalDate;
	private Date cTime;
	private Date mTime;
	private Set<?> wishLists = new HashSet<Object>(0);
	private Set<?> subscribedLists = new HashSet<Object>(0);

	public MemberDetails() {
	}

	public MemberDetails(MembershipDetails membershipDetails, UserDetails userDetails, Date enrolledDate, Date endDate,
			Date renewalDate, Date cTime, Date mTime) {
		this.membershipDetails = membershipDetails;
		this.userDetails = userDetails;
		this.enrolledDate = enrolledDate;
		this.endDate = endDate;
		this.renewalDate = renewalDate;
		this.cTime = cTime;
		this.mTime = mTime;
	}

	public MemberDetails(MembershipDetails membershipDetails, UserDetails userDetails, Date enrolledDate, Date endDate,
			Date renewalDate, Date cTime, Date mTime, Set<?> wishLists, Set<?> subscribedLists) {
		this.membershipDetails = membershipDetails;
		this.userDetails = userDetails;
		this.enrolledDate = enrolledDate;
		this.endDate = endDate;
		this.renewalDate = renewalDate;
		this.cTime = cTime;
		this.mTime = mTime;
		this.wishLists = wishLists;
		this.subscribedLists = subscribedLists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "member_id", unique = true, nullable = false)
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "membership_type_id", nullable = false)
	public MembershipDetails getMembershipDetails() {
		return this.membershipDetails;
	}

	public void setMembershipDetails(MembershipDetails membershipDetails) {
		this.membershipDetails = membershipDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enrolled_date", nullable = false, length = 10)
	public Date getEnrolledDate() {
		return this.enrolledDate;
	}

	public void setEnrolledDate(Date enrolledDate) {
		this.enrolledDate = enrolledDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "renewal_date", nullable = false, length = 10)
	public Date getRenewalDate() {
		return this.renewalDate;
	}

	public void setRenewalDate(Date renewalDate) {
		this.renewalDate = renewalDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", nullable = false, length = 19)
	public Date getcTime() {
		return this.cTime;
	}

	public void setcTime(Date cTime) {
		this.cTime = cTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", nullable = false, length = 19)
	public Date getmTime() {
		return this.mTime;
	}

	public void setmTime(Date mTime) {
		this.mTime = mTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memberDetails")
	public Set<?> getWishLists() {
		return this.wishLists;
	}

	public void setWishLists(Set<?> wishLists) {
		this.wishLists = wishLists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memberDetails")
	public Set<?> getSubscribedLists() {
		return this.subscribedLists;
	}

	public void setSubscribedLists(Set<?> subscribedLists) {
		this.subscribedLists = subscribedLists;
	}

}
