package com.training.pojos;
// default package
// Generated Sep 13, 2016 5:13:51 PM by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Movies generated by hbm2java
 */
@Entity
@Table(name = "movies", catalog = "onlinelibrary")
public class Movies implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String movieId;
	private LibraryItems libraryItems;
	private String productions;
	private String writers;
	private String singers;
	private String directors;
	private String casts;
	private Date releaseDate;
	private String genre;
	private Date cTime;
	private Date mTime;

	public Movies() {
	}

	public Movies(LibraryItems libraryItems, String productions, String writers, String singers, String directors,
			String casts, Date releaseDate, Date cTime, Date mTime) {
		this.libraryItems = libraryItems;
		this.productions = productions;
		this.writers = writers;
		this.singers = singers;
		this.directors = directors;
		this.casts = casts;
		this.releaseDate = releaseDate;
		this.cTime = cTime;
		this.mTime = mTime;
	}

	public Movies(LibraryItems libraryItems, String productions, String writers, String singers, String directors,
			String casts, Date releaseDate, String genre, Date cTime, Date mTime) {
		this.libraryItems = libraryItems;
		this.productions = productions;
		this.writers = writers;
		this.singers = singers;
		this.directors = directors;
		this.casts = casts;
		this.releaseDate = releaseDate;
		this.genre = genre;
		this.cTime = cTime;
		this.mTime = mTime;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "libraryItems"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "movie_id", unique = true, nullable = false, length = 8)
	public String getMovieId() {
		return this.movieId;
	}

	public void setMovieId(String movieId) {
		this.movieId = movieId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public LibraryItems getLibraryItems() {
		return this.libraryItems;
	}

	public void setLibraryItems(LibraryItems libraryItems) {
		this.libraryItems = libraryItems;
	}

	@Column(name = "productions", nullable = false, length = 100)
	public String getProductions() {
		return this.productions;
	}

	public void setProductions(String productions) {
		this.productions = productions;
	}

	@Column(name = "writers", nullable = false, length = 100)
	public String getWriters() {
		return this.writers;
	}

	public void setWriters(String writers) {
		this.writers = writers;
	}

	@Column(name = "singers", nullable = false, length = 100)
	public String getSingers() {
		return this.singers;
	}

	public void setSingers(String singers) {
		this.singers = singers;
	}

	@Column(name = "directors", nullable = false, length = 100)
	public String getDirectors() {
		return this.directors;
	}

	public void setDirectors(String directors) {
		this.directors = directors;
	}

	@Column(name = "casts", nullable = false, length = 100)
	public String getCasts() {
		return this.casts;
	}

	public void setCasts(String casts) {
		this.casts = casts;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "release_date", nullable = false, length = 10)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "genre", length = 20)
	public String getGenre() {
		return this.genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_time", nullable = false, length = 19)
	public Date getcTime() {
		return this.cTime;
	}

	public void setcTime(Date cTime) {
		this.cTime = cTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_time", nullable = false, length = 19)
	public Date getmTime() {
		return this.mTime;
	}

	public void setmTime(Date mTime) {
		this.mTime = mTime;
	}

}
