############################################# SPRING BOOT CONFIGURATION #####################################################
##########################################Spring Boot Application properties for and keystore configuration############
server:
  port: 8090
  
#  jsp-servlet.class-name: org.apache.cxf.jaxrs.servlet.CXFNonSpringJaxrsServlet
  #jsp-servlet.init-parameters:
    #jaxrs.serviceClasses: com.training.restservices.UserServices
#ssl.enabled: true
#ssl.key-store: springboottest.keystore
#ssl.key-store-password: javatest
#ssl.keyStoreType: PKCS12
#ssl.keyAlias: tomcat
#############################################################################################################################