############################################# SPRING BOOT CONFIGURATION #####################################################
##########################################Spring Boot Application properties for and keystore configuration############
server:
  port: 8080
  
#ssl.enabled: true
#ssl.key-store: springboottest.keystore
#ssl.key-store-password: javatest
#ssl.keyStoreType: PKCS12
#ssl.keyAlias: tomcat
#############################################################################################################################